altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  734ed54e-3a32-4887-845f-3ac1145c3645:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-13T15:02:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4ea57b5c-a87b-4c97-a76b-615c2a660a66
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c336abf6-a64f-4adb-ad4a-ce442ffce9aa
        userCondition: null
fs: images
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
